/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.calculator;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int edition=0x7f050003;
        public static final int equations=0x7f050000;
        public static final int plotter=0x7f050001;
        public static final int results=0x7f050002;
        public static final int submit_button=0x7f050004;
    }
    public static final class layout {
        public static final int equation_editor=0x7f030000;
        public static final int equation_plotter=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int equation_editor=0x7f040002;
        public static final int equation_plotter=0x7f040003;
        public static final int menu_eq_editor=0x7f040004;
        public static final int menu_eq_editor_add_equation=0x7f040006;
        public static final int menu_eq_editor_plot=0x7f040005;
        public static final int menu_eq_editor_remove_equation=0x7f040007;
        public static final int submit_button=0x7f040001;
    }
}
