/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Crinson_Blog_mainWnd */

#ifndef _Included_Crinson_Blog_mainWnd
#define _Included_Crinson_Blog_mainWnd
#ifdef __cplusplus
extern "C" 
{
#endif
/*
 * Class:     Crinson_Blog_mainWnd
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Crinson_Blog_mainWnd_setName(JNIEnv *_pEnv, jobject _obj, jstring _strName);

#ifdef __cplusplus
}
#endif
#endif
