/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.test_02;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int color=0x7f050000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int mCheckBox1=0x7f060000;
        public static final int mCheckBox2=0x7f060001;
        public static final int mTextView1=0x7f060002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int hello_2=0x7f040002;
        public static final int str_checkbox=0x7f040003;
    }
}
