// Copyright 2008 Google Inc.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Fri Jan 04 18:13:12 GMT 2008
//----------------------------------------------------

package com.google.calculator.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int DIVIDE = 8;
  public static final int NUMBER = 10;
  public static final int HAT = 9;
  public static final int LITTERAL = 11;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int error = 1;
  public static final int COMMA = 4;
  public static final int RPAREN = 3;
  public static final int TIMES = 7;
  public static final int LPAREN = 2;
}

